#!/bin/sh

set -e

case $1 in
    configure)
        if ! getent passwd consul > /dev/null 2>&1 ; then
            adduser --quiet --system --group --disabled-login --disabled-password --no-create-home --home /var/lib/consul consul
        fi
        chown -R consul:consul /var/lib/consul
        chown -R consul:consul /etc/consul.d
        chmod u+rwX,go-rwX  /var/lib/consul
    ;;
esac

#DEBHELPER#

exit 0
